from flask import Flask, render_template, request, jsonify, session

app = Flask(__name__)
app.secret_key = "creators-kit-secret"  # Change this to a secure key in production

# --------------------
# HOME / LOGIN
# --------------------
@app.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html")  # Optional: your landing page

# --------------------
# DYNAMIC PLATFORM ROUTES
# --------------------
@app.route("/<platform>")
def toolkit(platform):
    """
    Dynamically render the toolkit page for a platform.
    Expects template files like facebook.html, instagram.html, tiktok.html, etc.
    """
    template_name = f"{platform}.html"
    try:
        return render_template(template_name)
    except:
        return f"Page '{platform}' not found", 404

# --------------------
# USE TOOL ENDPOINT
# --------------------
@app.route("/use_tool", methods=["POST"])
def use_tool():
    """
    Handles content generated by JS for any platform/tool.
    Saves to DB or prints for now.
    """
    data = request.get_json()
    platform = data.get("platform")
    tool = data.get("tool")
    content = data.get("content")
    save = data.get("save", False)

    # For now: just print. Replace with DB logic if you want.
    if save:
        print(f"[SAVE] Platform: {platform} | Tool: {tool} | Content: {content}")

    return jsonify({"status": "success"})

# --------------------
# OPTIONAL: 404 HANDLER
# --------------------
@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404

# --------------------
# RUN APP
# --------------------
if __name__ == "__main__":
    app.run(debug=True)
